# Generated by Django 3.2.8 on 2024-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/chikawa,jpg', null=True, upload_to='profiles/'),
        ),
    ]
