# Generated by Django 3.2.8 on 2024-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='/projects/OnePiece.jpg', null=True, upload_to='projects/'),
        ),
    ]
